### ISSUE TITLE
add clientID tracking

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#3]
for records, we want to add clientID to default google analytics reporting so we can pull it down for our identity resolution model. Today I added it to google analytics and gtm for bensleycollection.com 

followed this guide, its setup, will monitor and make sure its coming through over the next few days and close.

https://www.optimizesmart.com/how-to-send-client-id-to-google-analytics-via-google-tag-manager/

**Comment by StrangeWill** [comment]
Arguably -- because we will have our own internal client IDs, we'll need to see about resolving both of them (we can get cross-device matching easily this way), the article just piggy backs the GA ID which can change across devices/browsers/fully cleared sessions/etc.

**Comment by paulchrisluke** [comment]
Segment has an integration with drip.com, who I plan to use for email... I say let's go for it. I'll make accounts tomorrow

**Comment by paulchrisluke** [comment]
Clientid is coming into analytics, that's pretty cool. I also made a segment account and attempted to link it. I linked it using their gui for *just* GTM integration, which should be automatically bringing in google analytics data. I *think* if you go through their gui we don't need to install their tracking script in our analytics <head> but I got a  bit confused by their documentation. Will come back around to segment in a couple days to verify data is coming in.

![image](https://user-images.githubusercontent.com/5694308/61710557-161c1580-ad7c-11e9-8301-13af8afd73d4.png)
![image](https://user-images.githubusercontent.com/5694308/61710573-1caa8d00-ad7c-11e9-95af-4df0d4b7f286.png)

**Comment by bamboochow** [comment]
This is @paulchrisluke just typing from Julias account. 

I can't tell is segment is collecting data.. I'll look into that later.

I was looking into how to properly attribute individual content sources. Previously, we used UTM's to track every bit of content and that worked well, but ran into some issues where our UTM was overwriting the [auto tagging](https://support.google.com/google-ads/answer/1752125?co=ADWORDS.IsAWNCustomer%3Dfalse&hl=en) done by google adwords and "caused issues" (thats from the ad buying team). I suppose in a way, I'm looking to build the same sot of auto tagger but one we control.

How we did it in the past using UTM's:
```
source (platform... facebook, instagram, mailchimp, linkedin)
medium (delivery method... cpc [paid ads], post, story, email)
content (content title)
```
Technically, all of that information should be known by meredith on content deploy, so she should be able to generate trackable links, maybe burying them in cute urls like gfycat does instead of showing the raw UTM. 

This would not solve the problem of other sources like CNN using none trackable links for our content... is there a way to detect the same information coming in automatically? Love your input @StrangeWill
